In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [140]:
class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

In [141]:
# Example usage
input_size = 10
hidden_size = 20
output_size = 5

In [142]:
# Create an instance of the SimpleNet class
net = SimpleNet(input_size, hidden_size, output_size)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

# Generate dummy input and target tensors
input_tensor = torch.randn(32, input_size)  # Batch size of 32
target_tensor = torch.empty(32, dtype=torch.float).random_(output_size)

In [143]:
target_tensor.dtype

torch.float32

In [144]:
target_tensor

tensor([0., 4., 2., 0., 0., 1., 0., 3., 0., 1., 2., 3., 4., 0., 4., 1., 3., 0.,
        1., 0., 0., 4., 0., 0., 2., 4., 4., 4., 0., 3., 4., 0.])

In [145]:
output = net(input_tensor)
loss = criterion(output, target_tensor)

RuntimeError: expected scalar type Long but found Float

In [86]:
loss = criterion(output, target_tensor)

In [85]:
output.shape

torch.Size([32, 5])

In [12]:
print(target_tensor.size())

torch.Size([32])


In [ ]:
# Training loop
for epoch in range(10):
    optimizer.zero_grad()  # Zero the gradients

    # Forward pass
    output = net(input_tensor)
    loss = criterion(output, target_tensor)

    # Backward pass and optimization
    loss.backward()
    optimizer.step()

    # Print loss for monitoring
    print(f"Epoch {epoch+1} - Loss: {loss.item()}")

# Use the trained model for inference
test_input = torch.randn(1, input_size)
output = net(test_input)
predicted_class = torch.argmax(output)

print(f"Predicted class: {predicted_class.item()}")

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

In [119]:
class mynet(nn.Module):
    def __init__(self,input_size, output_size):
        super(mynet, self).__init__()
        self.layer_1 = nn.Linear(input_size, output_size)
        self.layer_2 = nn.ReLU()
        self.layer_3 = nn.Linear(output_size, 1)
    
    def forward(self,input_):
        out = self.layer_1(input_)
        out = self.layer_2(out)
        out = self.layer_3(out)
        out = nn.Sigmoid()(out)
        return out

In [120]:
input_size = 10
output_size = 5

In [121]:
loss_fn = nn.BCELoss()
net = mynet(input_size,output_size)
optimizer = optim.SGD(net.parameters(), lr=0.01)

In [132]:
input_ = torch.rand(23,10)
target = torch.tensor([[torch.randint(0, 2, (1,)).item()] for j in range(23)], dtype=torch.float)

In [133]:
output = net(input_)

In [134]:
# loss_fn = nn.L1Loss()
loss = loss_fn(output, target)

In [125]:
target.dtype

torch.int64

In [136]:
for epoch in range(10):
    optimizer.zero_grad()  # Zero the gradients

    # Forward pass
    output = net(input_)
    loss = loss_fn(output, target)

    # Backward pass and optimization
    loss.backward()
    optimizer.step()

    # Print loss for monitoring
    print(f"Epoch {epoch+1} - Loss: {loss.item()}")

# Use the trained model for inference
test_input = torch.randn(1, input_size)
output = net(test_input)
print(output)

Epoch 1 - Loss: 0.6934698224067688
Epoch 2 - Loss: 0.6934133768081665
Epoch 3 - Loss: 0.693356990814209
Epoch 4 - Loss: 0.693300724029541
Epoch 5 - Loss: 0.693244457244873
Epoch 6 - Loss: 0.6931881308555603
Epoch 7 - Loss: 0.6931319236755371
Epoch 8 - Loss: 0.6930757761001587
Epoch 9 - Loss: 0.6930195093154907
Epoch 10 - Loss: 0.6929634213447571
tensor([[0.5661]], grad_fn=<SigmoidBackward0>)


In [2]:
a = torch.rand(10,5,20)

In [4]:
b = torch.rand(2,5)

In [13]:
b

tensor([[0.7497, 0.7714, 0.6330, 0.7394, 0.3230],
        [0.8572, 0.7300, 0.8965, 0.6324, 0.7801]])

In [17]:
b[:,-2:]

tensor([[0.7394, 0.3230],
        [0.6324, 0.7801]])

5